-- SYSTEM

-- check OLS registered and enabled 
SELECT STATUS FROM DBA_OLS_STATUS WHERE NAME = 'OLS_CONFIGURE_STATUS';
SELECT VALUE FROM V$OPTION WHERE PARAMETER = 'Oracle Label Security';

-- unlock LBACSYS
-- LBACSYS/lbacsys for policy management
ALTER USER LBACSYS ACCOUNT UNLOCK IDENTIFIED BY lbacsys;

-- cs5322/cs5322 for schema
CREATE USER cs5322 IDENTIFIED BY cs5322;
GRANT CONNECT, RESOURCE, DBA TO cs5322;
GRANT UNLIMITED TABLESPACE TO cs5322;
GRANT CREATE SESSION TO cs5322;

-- test user
CREATE USER guest IDENTIFIED BY guest;
GRANT CONNECT TO guest;
GRANT CREATE SESSION TO guest;

CREATE USER student IDENTIFIED BY student;
GRANT CONNECT TO student;
GRANT CREATE SESSION TO student;

CREATE USER professor IDENTIFIED BY professor;
GRANT CONNECT TO professor;
GRANT CREATE SESSION TO professor;

CREATE USER op_staff IDENTIFIED BY op_staff;
GRANT CONNECT TO op_staff;
GRANT CREATE SESSION TO op_staff;

CREATE USER op_director IDENTIFIED BY op_director;
GRANT CONNECT TO op_director;
GRANT CREATE SESSION TO op_director;

CREATE USER fn_staff IDENTIFIED BY fn_staff;
GRANT CONNECT TO fn_staff;
GRANT CREATE SESSION TO fn_staff;

CREATE USER fn_director IDENTIFIED BY fn_director;
GRANT CONNECT TO fn_director;
GRANT CREATE SESSION TO fn_director;

SELECT * FROM dba_users WHERE ACCOUNT_STATUS='OPEN'; 
-- DROP USER cs5322 CASCADE;